# Generated by Django 5.2.10 on 2026-01-28 07:23

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RiskState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('starting_balance', models.DecimalField(decimal_places=8, max_digits=18)),
                ('current_balance', models.DecimalField(decimal_places=8, max_digits=18)),
                ('highest_balance', models.DecimalField(decimal_places=8, max_digits=18)),
                ('daily_pnl', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=18)),
                ('daily_pnl_pct', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=8)),
                ('drawdown', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=18)),
                ('drawdown_pct', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=8)),
                ('max_drawdown_pct', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=8)),
                ('total_trades', models.IntegerField(default=0)),
                ('winning_trades', models.IntegerField(default=0)),
                ('losing_trades', models.IntegerField(default=0)),
                ('system_status', models.CharField(choices=[('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('EMERGENCY_STOP', 'Emergency Stop')], default='ACTIVE', max_length=20)),
                ('pause_reason', models.CharField(blank=True, max_length=200)),
                ('paused_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Risk State',
                'verbose_name_plural': 'Risk States',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='EconomicEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('CPI', 'Consumer Price Index'), ('PPI', 'Producer Price Index'), ('NFP', 'Non-Farm Payrolls'), ('FOMC', 'Federal Reserve Meeting'), ('GDP', 'Gross Domestic Product'), ('OTHER', 'Other')], max_length=10)),
                ('country', models.CharField(default='US', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('release_time', models.DateTimeField(db_index=True)),
                ('forecast', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('actual', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('previous', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('impact', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=10)),
                ('deviation_from_forecast', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('source', models.CharField(max_length=50)),
                ('external_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-release_time'],
                'unique_together': {('event_type', 'country', 'release_time')},
            },
        ),
        migrations.CreateModel(
            name='MarketData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('timeframe', models.CharField(max_length=10)),
                ('open_time', models.DateTimeField(db_index=True)),
                ('open_price', models.DecimalField(decimal_places=8, max_digits=18)),
                ('high_price', models.DecimalField(decimal_places=8, max_digits=18)),
                ('low_price', models.DecimalField(decimal_places=8, max_digits=18)),
                ('close_price', models.DecimalField(decimal_places=8, max_digits=18)),
                ('volume', models.DecimalField(decimal_places=8, max_digits=24)),
                ('close_time', models.DateTimeField()),
                ('quote_volume', models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True)),
                ('trade_count', models.IntegerField(blank=True, null=True)),
                ('spread', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('body', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('upper_wick', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('lower_wick', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('close_position', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
            ],
            options={
                'ordering': ['-open_time'],
                'indexes': [models.Index(fields=['symbol', 'timeframe', 'open_time'], name='trading_mar_symbol_fd3243_idx')],
                'unique_together': {('symbol', 'timeframe', 'open_time')},
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('binance_order_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('binance_client_order_id', models.CharField(blank=True, max_length=64)),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('side', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4)),
                ('order_type', models.CharField(default='LIMIT', max_length=20)),
                ('requested_quantity', models.DecimalField(decimal_places=8, max_digits=18)),
                ('filled_quantity', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=18)),
                ('requested_price', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('execution_price', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('average_price', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('expected_price', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('slippage', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=18)),
                ('slippage_pct', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=8)),
                ('pnl', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=18)),
                ('pnl_pct', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=8)),
                ('commission', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=18)),
                ('macro_context', models.CharField(blank=True, max_length=200)),
                ('vpa_signal', models.CharField(blank=True, max_length=50)),
                ('three_d_signal', models.CharField(blank=True, max_length=50)),
                ('ema_deviation', models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PARTIALLY_FILLED', 'Partially Filled'), ('FILLED', 'Filled'), ('CANCELLED', 'Cancelled'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filled_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['symbol', 'status'], name='trading_tra_symbol_abb7cc_idx'), models.Index(fields=['created_at'], name='trading_tra_created_a5fdbf_idx')],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('side', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4)),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=18)),
                ('entry_price', models.DecimalField(decimal_places=8, max_digits=18)),
                ('current_price', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('unrealized_pnl', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=18)),
                ('unrealized_pnl_pct', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=8)),
                ('initial_stop', models.DecimalField(decimal_places=8, max_digits=18)),
                ('current_stop', models.DecimalField(decimal_places=8, max_digits=18)),
                ('trailing_activated', models.BooleanField(default=False)),
                ('trailing_distance', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('highest_price', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('lowest_price', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('take_profit', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=10)),
                ('close_reason', models.CharField(blank=True, max_length=50)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('entry_trade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='positions', to='trading.trade')),
                ('exit_trade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='closed_positions', to='trading.trade')),
            ],
            options={
                'ordering': ['-opened_at'],
                'indexes': [models.Index(fields=['symbol', 'status'], name='trading_pos_symbol_e13b5c_idx')],
            },
        ),
    ]
